---
- hosts: slave
  gather_facts: True
  vars:
      mn_root: /test_files/
      File_Loc: "{{ mn_root }}/"
      File_Name: Flex.zip
      Temp_File_Dest: /tmp/www/
      Temp_Dest: /tmp/
      War_File: Isrc.war
      web_root: /var/www/html/
  tasks:

   - name: Find file in given path to extract
     find:
      paths: "{{ mn_root }}/build" 
      patterns: Isrc.war
      recurse: true
     register: path_content

   - name : extract war file to required path
     unarchive:
      src: "{{ path_content.files[0].path }}"
      dest: "{{ web_root }}"
      remote_src: true
     when: path_content.matched

