---
# tasks file for srk-maskpass
- name : copy props to tmp folder
  copy :
   src : /var/log/tpass.log
   dest : /tmp/tpass
   remote_src : yes
   mode : 0644

- name : mask passwords in tmp props file 
  replace :
   path: /tmp/tpass
   regexp: '(=.* )'
   replace: '=XXXX'

- name : fetch the masked props to local
  fetch:
   src: /tmp/tpass
   dest: "/tmp/{{ inventory_hostname }}/tpass"
   flat: yes
